name: HS-Core
version: 5.3
author: RySty
main: mc.rysty.heliosphereplugin.HelioSpherePlugin
softdepend: [ViaVersion, ProtocolSupport]
api-version: 1.16

commands:
  gma:
  gmc:
  gmsp:
  gms: 
  commandspy:
    aliases: [cmdspy]
  broadcast:
    aliases: [bcast]
  fly:
  chat:
  clear:
    aliases: [ci]
  invsee:
    aliases: [inventorysee]
  echest:
    aliases: [enderchest, ec, echest]
  playerinfo:
    aliases: [whois]
  serverinfo:
    aliases: [sinfo]
  invincible:
  hs-core:
  afk:
    aliases: [idle]
  nickname:
    aliases: [nick]
  staffchat:
    aliases: [sc]
  toggleblockmodify:
  vanish: 
    aliases: [v]
  heal:
  see:
  say:
  console:
  ping:
  i:
  sudo:
  feed:
  versionlist:
    aliases: [verlist]
  mute:   
  rename:
  hat:
  head:
    aliases: [playerhead]
 